In [27]:
import pymysql
import json
from pandas.io.json import json_normalize

try:
    # For Python 3.0 and later
    from urllib.request import urlopen
except ImportError:
    # Fall back to Python 2's urllib2
    from urllib2 import urlopen

def get_jsonparsed_data(url):
    response = urlopen(url)
    data = json.loads(response.read().decode("utf-8"))
    df = json_normalize(data['financials'])
    return df

url = ("https://financialmodelingprep.com/api/v3/financials/balance-sheet-statement/AAPL?period=quarter")
df = get_jsonparsed_data(url)

pandas.core.frame.DataFrame

In [9]:
json_normalize(data["financials"])

,Cash and cash equivalents,Cash and short-term investments,Deferred revenue,Deposit Liabilities,Goodwill and Intangible Assets,Inventories,Investments,Long-term debt,Long-term investments,Net Debt,...,Tax assets,Total assets,Total current assets,Total current liabilities,Total debt,Total liabilities,Total non-current assets,Total non-current liabilities,Total shareholders equity,date
0,50530000000.0,94614000000.0,5434000000.0,0.0,0.0,3355000000.0,160080000000.0,84936000000.0,115996000000.0,13804000000.0,...,0.0,322239000000.0,187266000000.0,89704000000.0,108418000000.0,225783000000.0,136079000000.0,136079000000.0,96456000000.0,2019-06-29
1,37988000000.0,80092000000.0,5532000000.0,0.0,0.0,4884000000.0,187423000000.0,90201000000.0,145319000000.0,32538000000.0,...,0.0,341998000000.0,218652000000.0,93772000000.0,112630000000.0,236138000000.0,142366000000.0,142366000000.0,105860000000.0,2019-03-30
2,44771000000.0,86427000000.0,5546000000.0,0.0,0.0,4988000000.0,200264000000.0,92989000000.0,158608000000.0,28303000000.0,...,0.0,373719000000.0,232891000000.0,108283000000.0,114730000000.0,255827000000.0,147544000000.0,147544000000.0,117892000000.0,2018-12-29
3,25913000000.0,66301000000.0,5966000000.0,0.0,0.0,3956000000.0,211187000000.0,93735000000.0,170799000000.0,48182000000.0,...,0.0,365725000000.0,234386000000.0,115929000000.0,114483000000.0,258578000000.0,142649000000.0,142649000000.0,107147000000.0,2018-09-29
4,31971000000.0,70970000000.0,10281000000.0,0.0,0.0,5936000000.0,211772000000.0,97128000000.0,172773000000.0,43630000000.0,...,0.0,349197000000.0,233436000000.0,88548000000.0,114600000000.0,234248000000.0,145700000000.0,145700000000.0,114949000000.0,2018-06-30
5,45059000000.0,87940000000.0,10862000000.0,0.0,0.0,7662000000.0,222167000000.0,101362000000.0,179286000000.0,33900000000.0,...,0.0,367502000000.0,237449000000.0,89320000000.0,121840000000.0,240624000000.0,151304000000.0,151304000000.0,126878000000.0,2018-03-31
6,27491000000.0,77153000000.0,11175000000.0,0.0,8038000000.0,4421000000.0,257606000000.0,103922000000.0,207944000000.0,45247000000.0,...,0.0,406794000000.0,262984000000.0,115788000000.0,122400000000.0,266595000000.0,150807000000.0,150807000000.0,140199000000.0,2017-12-30
7,20289000000.0,74181000000.0,10384000000.0,0.0,0.0,4855000000.0,248606000000.0,97207000000.0,194714000000.0,41499000000.0,...,0.0,375319000000.0,246674000000.0,100814000000.0,115680000000.0,241272000000.0,140458000000.0,140458000000.0,134047000000.0,2017-09-30
8,18571000000.0,76759000000.0,10592000000.0,0.0,8105000000.0,3146000000.0,242945000000.0,89864000000.0,184757000000.0,31580000000.0,...,0.0,345173000000.0,232298000000.0,81302000000.0,108339000000.0,212748000000.0,131446000000.0,131446000000.0,132425000000.0,2017-07-01
9,15157000000.0,67101000000.0,10789000000.0,0.0,8090000000.0,2910000000.0,241684000000.0,84531000000.0,189740000000.0,31421000000.0,...,0.0,334532000000.0,232542000000.0,73342000000.0,98522000000.0,200450000000.0,127108000000.0,127108000000.0,134082000000.0,2017-04-01
10,16371000000.0,60452000000.0,11052000000.0,0.0,8271000000.0,2712000000.0,229719000000.0,73557000000.0,185638000000.0,27097000000.0,...,0.0,331141000000.0,227809000000.0,84130000000.0,87549000000.0,198751000000.0,114621000000.0,114621000000.0,132390000000.0,2016-12-31
11,20484000000.0,67155000000.0,11010000000.0,0.0,8620000000.0,2132000000.0,217101000000.0,75427000000.0,170430000000.0,19877000000.0,...,0.0,321686000000.0,214817000000.0,79006000000.0,87032000000.0,193437000000.0,114431000000.0,114431000000.0,128249000000.0,2016-09-24
12,18237000000.0,61756000000.0,11416000000.0,0.0,8767000000.0,1831000000.0,213283000000.0,68939000000.0,169764000000.0,23179000000.0,...,0.0,305602000000.0,211841000000.0,71486000000.0,84935000000.0,179061000000.0,107575000000.0,107575000000.0,126541000000.0,2016-06-25
13,21514000000.0,55283000000.0,12783000000.0,0.0,9092000000.0,2281000000.0,211414000000.0,69374000000.0,177645000000.0,24589000000.0,...,0.0,305277000000.0,217685000000.0,68265000000.0,79872000000.0,174820000000.0,106555000000.0,106555000000.0,130457000000.0,2016-03-26
14,16689000000.0,38074000000.0,12535000000.0,0.0,9126000000.0,2451000000.0,199050000000.0,53204000000.0,177665000000.0,24889000000.0,...,0.0,293284000000.0,217065000000.0,76092000000.0,62963000000.0,165017000000.0,88925000000.0,88925000000.0,128267000000.0,2015-12-26
15,21120000000.0,41601000000.0,12564000000.0,0.0,9009000000.0,2349000000.0,184546000000.0,53329000000.0,164065000000.0,22727000000.0,...,0.0,290345000000.0,200967000000.0,80610000000.0,64328000000.0,170990000000.0,90380000000.0,90380000000.0,119355000000.0,2015-09-26
16,15319000000.0,34703000000.0,12562000000.0,0.0,8823000000.0,2042000000.0,187529000000.0,47419000000.0,168145000000.0,19715000000.0,...,5010000000.0,273151000000.0,202198000000.0,65285000000.0,54418000000.0,147474000000.0,82189000000.0,82189000000.0,125677000000.0,2015-06-27
17,14489000000.0,33096000000.0,12515000000.0,0.0,8772000000.0,2396000000.0,179050000000.0,40072000000.0,160443000000.0,10775000000.0,...,5141000000.0,261194000000.0,193303000000.0,58729000000.0,43871000000.0,132188000000.0,73459000000.0,73459000000.0,129006000000.0,2015-03-28
18,19478000000.0,32463000000.0,12467000000.0,0.0,8999000000.0,2283000000.0,158477000000.0,32504000000.0,145492000000.0,3940000000.0,...,5046000000.0,261894000000.0,178491000000.0,73611000000.0,36403000000.0,138566000000.0,64955000000.0,64955000000.0,123328000000.0,2014-12-27
19,13844000000.0,25077000000.0,11522000000.0,0.0,8758000000.0,2111000000.0,141395000000.0,28987000000.0,130162000000.0,10218000000.0,...,4318000000.0,231839000000.0,163308000000.0,63448000000.0,35295000000.0,120292000000.0,56844000000.0,56844000000.0,111547000000.0,2014-09-27
20,12977000000.0,37805000000.0,11454000000.0,0.0,6141000000.0,1594000000.0,151513000000.0,29030000000.0,126685000000.0,-6765000000.0,...,3884000000.0,222520000000.0,154571000000.0,46205000000.0,31040000000.0,101580000000.0,55375000000.0,55375000000.0,120940000000.0,2014-06-28
21,18949000000.0,41350000000.0,11474000000.0,0.0,5983000000.0,1829000000.0,131640000000.0,16962000000.0,109239000000.0,-24388000000.0,...,4014000000.0,205989000000.0,135448000000.0,43208000000.0,16962000000.0,85810000000.0,42602000000.0,42602000000.0,120179000000.0,2014-03-29
22,14077000000.0,40711000000.0,11428000000.0,0.0,6127000000.0,2122000000.0,144765000000.0,16961000000.0,118131000000.0,-23750000000.0,...,3742000000.0,225184000000.0,144837000000.0,53769000000.0,16961000000.0,95500000000.0,41731000000.0,41731000000.0,129684000000.0,2013-12-28
23,14259000000.0,40546000000.0,10060000000.0,0.0,5756000000.0,1764000000.0,132502000000.0,16960000000.0,106215000000.0,-23586000000.0,...,3453000000.0,207000000000.0,133714000000.0,43658000000.0,16960000000.0,83451000000.0,39793000000.0,39793000000.0,123549000000.0,2013-09-28
24,11248000000.0,42606000000.0,10005000000.0,0.0,5875000000.0,1697000000.0,135372000000.0,16958000000.0,104014000000.0,-25648000000.0,...,3193000000.0,199856000000.0,131637000000.0,36319000000.0,16958000000.0,76502000000.0,40183000000.0,40183000000.0,123354000000.0,2013-06-29
25,12053000000.0,39137000000.0,10142000000.0,0.0,5536000000.0,1245000000.0,132634000000.0,0.0,105550000000.0,-39137000000.0,...,3242000000.0,194743000000.0,131406000000.0,35508000000.0,0.0,59253000000.0,23745000000.0,23745000000.0,135490000000.0,2013-03-30
26,16154000000.0,39820000000.0,10212000000.0,0.0,5843000000.0,1455000000.0,120958000000.0,0.0,97292000000.0,-39820000000.0,...,2895000000.0,196088000000.0,123740000000.0,46879000000.0,0.0,68742000000.0,21863000000.0,21863000000.0,127346000000.0,2012-12-29
27,10746000000.0,29129000000.0,8601000000.0,0.0,5359000000.0,791000000.0,110505000000.0,0.0,92122000000.0,-29129000000.0,...,2583000000.0,176064000000.0,118411000000.0,38542000000.0,0.0,57854000000.0,19312000000.0,19312000000.0,118210000000.0,2012-09-29
28,7945000000.0,27654000000.0,8352000000.0,0.0,5461000000.0,1122000000.0,109276000000.0,0.0,89567000000.0,-27654000000.0,...,2309000000.0,162896000000.0,110953000000.0,33060000000.0,0.0,51150000000.0,18090000000.0,18090000000.0,111746000000.0,2012-06-30
29,10121000000.0,28538000000.0,7693000000.0,0.0,4745000000.0,1102000000.0,100055000000.0,0.0,81638000000.0,-28538000000.0,...,2253000000.0,150934000000.0,100222000000.0,32036000000.0,0.0,48436000000.0,16400000000.0,16400000000.0,102498000000.0,2012-03-31
30,10310000000.0,30156000000.0,7073000000.0,0.0,4368000000.0,1236000000.0,87291000000.0,0.0,67445000000.0,-30156000000.0,...,1937000000.0,138681000000.0,83910000000.0,34607000000.0,0.0,48627000000.0,14020000000.0,14020000000.0,90054000000.0,2011-12-31
31,9815000000.0,25952000000.0,5777000000.0,0.0,4432000000.0,776000000.0,71755000000.0,0.0,55618000000.0,-25952000000.0,...,2014000000.0,116371000000.0,71383000000.0,27970000000.0,0.0,39756000000.0,11786000000.0,11786000000.0,76615000000.0,2011-09-24
32,12091000000.0,28395000000.0,5399000000.0,0.0,1910000000.0,889000000.0,64065000000.0,0.0,47761000000.0,-28395000000.0,...,1892000000.0,106758000000.0,59860000000.0,26859000000.0,0.0,37415000000.0,10556000000.0,10556000000.0,69343000000.0,2011-06-25
33,15978000000.0,29234000000.0,4821000000.0,0.0,1248000000.0,930000000.0,49789000000.0,0.0,36533000000.0,-29234000000.0,...,1683000000.0,94904000000.0,47907000000.0,24327000000.0,0.0,33427000000.0,9100000000.0,9100000000.0,61477000000.0,2011-03-26
34,10734000000.0,26977000000.0,4757000000.0,0.0,1263000000.0,885000000.0,48973000000.0,0.0,32730000000.0,-26977000000.0,...,1724000000.0,86742000000.0,42815000000.0,23795000000.0,0.0,32076000000.0,8281000000.0,8281000000.0,54666000000.0,2010-12-25
35,11261000000.0,25620000000.0,4123000000.0,0.0,1083000000.0,1051000000.0,39750000000.0,0.0,25391000000.0,-25620000000.0,...,1636000000.0,75183000000.0,33505000000.0,20722000000.0,0.0,27392000000.0,6670000000.0,6670000000.0,47791000000.0,2010-09-25
36,9705000000.0,24288000000.0,3712000000.0,0.0,1032000000.0,942000000.0,36134000000.0,0.0,21551000000.0,-24288000000.0,...,1216000000.0,64725000000.0,28692000000.0,15612000000.0,0.0,21614000000.0,6002000000.0,6002000000.0,43111000000.0,2010-06-26
37,10018000000.0,23155000000.0,3483000000.0,0.0,743000000.0,638000000.0,31686000000.0,0.0,18549000000.0,-23155000000.0,...,1142000000.0,57057000000.0,24721000000.0,12229000000.0,0.0,17709000000.0,5480000000.0,5480000000.0,39348000000.0,2010-03-27
38,7609000000.0,24796000000.0,3512000000.0,0.0,494000000.0,576000000.0,32211000000.0,0.0,15024000000.0,-24796000000.0,...,1180000000.0,53926000000.0,20594000000.0,13097000000.0,0.0,18158000000.0,5061000000.0,5061000000.0,35768000000.0,2009-12-26
39,5263000000.0,23464000000.0,2906000000.0,0.0,453000000.0,455000000.0,28729000000.0,0.0,10528000000.0,-23464000000.0,...,1135000000.0,47501000000.0,15946000000.0,11506000000.0,0.0,15861000000.0,4355000000.0,4355000000.0,31640000000.0,2009-09-26
40,5605000000.0,24222000000.0,12136000000.0,0.0,466000000.0,380000000.0,25516000000.0,0.0,6899000000.0,-24222000000.0,...,1731000000.0,48140000000.0,12970000000.0,16661000000.0,0.0,22252000000.0,5591000000.0,5591000000.0,25888000000.0,2009-06-27

In [18]:
db = pymysql.connect("localhost","root","Joia0341##","xmedia" )

# prepare a cursor object using cursor() method
cursor = db.cursor()

# execute SQL query using execute() method.
cursor.execute("SELECT VERSION()")

# Fetch a single row using fetchone() method.
data = cursor.fetchone()
print ("Database version : %s " % data)

# disconnect from server
#db.close()

Database version : 5.7.26-log

In [20]:
cursor.execute("DROP TABLE IF EXISTS EMPLOYEE")

# Create table as per requirement
sql = """'Cash and cash equivalents, Cash and short-term investments, Deferred revenue, Deposit Liabilities,\
Goodwill and Intangible Assets, Inventories, Investments, Long-term debt, Long-term investments, Net Debt,\
Other Assets, Other Liabilities, Other comprehensive income, Payables, Property, Plant & Equipment Net,\
Receivables, Retained earnings (deficit), Short-term debt, Short-term investments, Tax Liabilities,\
Tax assets, Total assets, Total current assets, Total current liabilities, Total debt, Total liabilities,\
Total non-current assets, Total non-current liabilities, Total shareholders equity, date\

'"""

cursor.execute(sql)

In [37]:

columns_insert = ', '.join(str(elem) for elem in df.columns)
columns_insert
values_insert= "%s, "*30

In [38]:
columns_insert

'Cash and cash equivalents, Cash and short-term investments, Deferred revenue, Deposit Liabilities, Goodwill and Intangible Assets, Inventories, Investments, Long-term debt, Long-term investments, Net Debt, Other Assets, Other Liabilities, Other comprehensive income, Payables, Property, Plant & Equipment Net, Receivables, Retained earnings (deficit), Short-term debt, Short-term investments, Tax Liabilities, Tax assets, Total assets, Total current assets, Total current liabilities, Total debt, Total liabilities, Total non-current assets, Total non-current liabilities, Total shareholders equity, date'

In [68]:
user = 'root'
passw = 'Joia0341##'
host =  '172.17.0.2'
port = 3306
database = 'xmedia'

conn = pymysql.connect(host=host, port=port, user=user, passwd=passw)

conn.cursor().execute("CREATE DATABASE IF NOT EXISTS {0} ".format(database))
conn = pymysql.connect(host=host,
                       port=port,
                       user=user, 
                       passwd=passw,  
                       db=database,
                       charset='utf8')

data.to_sql(name=database, con=conn, if_exists = 'replace', index=False, flavor = 'mysql')

OperationalError: (2003, "Can't connect to MySQL server on '172.17.0.2' (timed out)")

In [49]:
import sqlalchemy as sa
import pandas as pd
from sqlalchemy import create_engine

In [66]:
cnx = create_engine('mysql+pymysql://[root]:[Joia0341##]@[172.17.0.2]:[3306]/[xmedia]', echo=False)
#df.to_sql("table_name", e, if_exists="replace", index=False)

In [67]:
data3 = pd.read_sql('SELECT * FROM testtable', cnx)

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '172.17.0.2]:[3306' ([Errno 11004] getaddrinfo failed)") (Background on this error at: http://sqlalche.me/e/e3q8)

In [55]:
cnx

Engine(mysql+pymysql://[host]:***@[172.17.0.2]:[3306]/[xmedia])

In [58]:
import pandas as pd
import pymysql
from sqlalchemy import create_engine


user = 'root'
passw = 'Joia0341##'
host =  '172.17.0.2'
port = 3306
database = 'xmedia'


mydb = create_engine('mysql+pymysql://' + user + ':' + passw + '@' + host + ':' + str(port) + '/' + database , echo=False)

In [59]:
mydb

Engine(mysql+pymysql://root:***@172.17.0.2:3306/xmedia)

In [65]:
data.to_sql(name=database, con=mydb, if_exists = 'append', index=False, flavor = 'mysql')

TypeError: to_sql() got an unexpected keyword argument 'flavor'

In [64]:
pd.io.sql._SQLALCHEMY_INSTALLED = True